version: '2'

networks:
  app-tier:
    driver: bridge

services:
  etcd-server:
    image: 'bitnami/etcd:latest'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd-server:2379
    ports:
      - 2379:2379
      - 2380:2380
    networks:
      - app-tier
  myapp:
    build: .
    ports:
      - 8000:8000
    networks:
      - app-tier
    depends_on:
      - etcd-server
