[api]
api_port=":8000"
write_timeout="15s"
read_timeout="15s"

[logs]
format="text"
log_level="debug"
log_dst="log.txt"

[etcd]
address=["127.0.0.1:2379","etcd-server:2379"]
dial_timeout="10s"
request_timeout="5m"